<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Waktu Penugasan</name>
   <tag></tag>
   <elementGuidId>c12f0304-435e-454a-9378-1d60bb4c78ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='mytable']/tbody/tr[10]/td[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mytable&quot;]/tbody/tr[${tr}]/td[${td}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mytable&quot;]/tbody/tr[${tr}]/td[${td}]</value>
      <webElementGuid>f3f664bc-0d48-4e3f-9a79-d4ef9b511988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mytable</value>
      <webElementGuid>32c8341f-9bf6-44dc-ae47-0e67f5db517f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mytable']/tbody/tr[${tr}]/td[${td}]</value>
      <webElementGuid>cbc0cad0-5515-4179-a9c2-30c277cae0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[66]/following::td[1]</value>
      <webElementGuid>409e8f5d-10f2-4c11-b882-22a337e1fea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[65]/following::td[2]</value>
      <webElementGuid>f27d6f7e-3f0b-4d94-ad7f-80a5fed7ce8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[68]/preceding::td[1]</value>
      <webElementGuid>33bf8259-a621-4086-89ad-5dcdfcae04e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[${tr}]/td[${td}]</value>
      <webElementGuid>01a44854-f7e1-4b2e-a106-6f1865567775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4ced60e3-3d3b-4cad-baaf-db0a2eb31f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
