<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Waktu Penugasan</name>
   <tag></tag>
   <elementGuidId>c12f0304-435e-454a-9378-1d60bb4c78ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[2]/div/div/div/div/div[4]/div[4]/div[2]/div/div[3]/div[1]/div/table/tbody/tr[${tr}]/td[${td}]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='mytable']/tbody/tr[10]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[2]/div[2]/div/div/div/div/div[4]/div[4]/div[2]/div/div[3]/div[1]/div/table/tbody/tr[${tr}]/td[${td}]</value>
      <webElementGuid>dd0e09e2-8394-41e1-996f-ef2be5a5d916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mytable</value>
      <webElementGuid>787e9f45-5595-4384-a359-c94a29057594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mytable']/tbody/tr[${tr}]/td[${td}]</value>
      <webElementGuid>438f54ae-bc59-4cb1-b95d-0ae3b5490bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[66]/following::td[1]</value>
      <webElementGuid>4e85f1ee-3526-40d7-ae4d-4b1663ba5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[65]/following::td[2]</value>
      <webElementGuid>2d6f188f-f723-4259-bdfb-d53fc9ad8510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[68]/preceding::td[1]</value>
      <webElementGuid>b5022ba8-d45f-4702-906e-6017205db552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[${tr}]/td[${td}]</value>
      <webElementGuid>caf2f317-d837-4fc5-9ce7-2ba49a5054af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a4b43f1e-a6e5-440a-95a7-fd62be639054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
