<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Program Marketing</name>
   <tag></tag>
   <elementGuidId>acd5e474-bcf2-4cd6-89dc-526f4140cfcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'REGULAR' or . = 'REGULAR')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-66-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-66-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74909132-50b3-48c8-a1a0-0d18efab97a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>d6512cd0-91b4-46f0-a3f2-6f923114a50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-66-option-${id}</value>
      <webElementGuid>ffc61fdf-4030-4f30-9167-d2815a951415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a92c4ef6-ff01-4aab-93b8-0148bbf69ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGULAR</value>
      <webElementGuid>f5d64f14-2a41-44b2-aa7e-5ff095b86356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-66-option-${id}&quot;)</value>
      <webElementGuid>f2766658-2841-4a5e-b5c4-6d940f38cc3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-66-option-2']</value>
      <webElementGuid>638afc0a-295a-48c7-92a3-0515367fc033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENCAIRAN &lt; 3 JT'])[1]/following::div[1]</value>
      <webElementGuid>ab6bf944-d40b-455d-9045-4ece2d760368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AYOOO SEKOLAAAH!'])[1]/following::div[2]</value>
      <webElementGuid>3d8374ce-a857-41c7-89d5-afbc9b6c0248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::div[1]</value>
      <webElementGuid>e790fc4a-3637-482a-84cf-d2557c5960d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGULAR']/parent::*</value>
      <webElementGuid>bb7337cb-809e-4190-bd4c-f3e267bca1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[3]</value>
      <webElementGuid>6c665d33-3b07-43c6-96f5-96b6c594fb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-66-option-2' and (text() = 'REGULAR' or . = 'REGULAR')]</value>
      <webElementGuid>c09d10cd-1927-424a-b2e6-012db3126839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
