<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Tahun</name>
   <tag></tag>
   <elementGuidId>c055396a-4123-41e3-8fdf-dadf73926dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '2019' or . = '2019')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-65-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-65-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b93c8ad-f8b6-4747-860f-8c8b809662bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>e40914ca-c33b-430b-af27-f970c28784ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-65-option-${id}</value>
      <webElementGuid>f0f7b22e-292b-4592-b660-f06d85ee3b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>82133aa4-bdfc-49e0-8d47-069f602f1ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2019</value>
      <webElementGuid>54cc653f-13f8-4f59-8875-2e65bf9dea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-65-option-${id}&quot;)</value>
      <webElementGuid>7d9c302c-c2a7-4384-becb-5734b0db7af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-65-option-2']</value>
      <webElementGuid>dbc2f78c-ef3b-4374-bf5d-13b26bb861cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tahun ...'])[1]/following::div[10]</value>
      <webElementGuid>d5cd9406-9d2d-44c5-bca2-f579688cf679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[14]</value>
      <webElementGuid>a67b2c12-a269-4f81-bf65-6a9d2925af3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Nilai Pencairan'])[1]/preceding::div[8]</value>
      <webElementGuid>0b4504af-885e-4c54-89d0-d3e8834bab3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus di isi !'])[1]/preceding::div[8]</value>
      <webElementGuid>06bf7434-5a7e-407d-9c31-ffc446c94cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2019']/parent::*</value>
      <webElementGuid>413ee030-ef11-48e0-8c36-2269ec4c3109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[3]</value>
      <webElementGuid>e9441bac-406d-486d-9cce-ae6d2c9b0166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-65-option-2' and (text() = '2019' or . = '2019')]</value>
      <webElementGuid>1021e279-14df-4f1c-ba03-55e98c427296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
