<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Aktivitas Marketing</name>
   <tag></tag>
   <elementGuidId>a3232255-b623-4d1d-b7f2-cd48ae86a91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'SELLING DAY' or . = 'SELLING DAY')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-67-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-67-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3927d8a-6943-4d0a-baaa-120c61a93788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>b8da28a0-41f8-471c-9de9-a06b2e2a9604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-67-option-${id}</value>
      <webElementGuid>5c0eec68-9f49-4d9a-b5a8-6814bdf4a3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7a1aa6ca-6506-41e1-a2af-b5ab7f8429e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELLING DAY</value>
      <webElementGuid>580d88e2-c1f9-433a-b75a-9081237655bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-67-option-${id}&quot;)</value>
      <webElementGuid>f4919536-6709-4afd-b854-b666a8160f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-67-option-2']</value>
      <webElementGuid>21b630eb-81e2-4fb5-86ee-19ca04d7cae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GREBEK PASAR'])[1]/following::div[1]</value>
      <webElementGuid>d547f7ad-11f6-44fa-8c27-d4609217a7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GATHERING MAGNET'])[1]/following::div[2]</value>
      <webElementGuid>19a428c3-18c4-41fd-a396-b07571fabd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto BPKB Identitas Pemilik'])[1]/preceding::div[2]</value>
      <webElementGuid>28085f85-56fc-4b7a-82f2-10a8af64501c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELLING DAY']/parent::*</value>
      <webElementGuid>f275a64e-3531-4927-9218-95726276ff30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[3]</value>
      <webElementGuid>f1db55d6-03f0-49f2-8710-39c435d25d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-67-option-2' and (text() = 'SELLING DAY' or . = 'SELLING DAY')]</value>
      <webElementGuid>6c23b752-1ba8-4829-81da-3e730846f1f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
