<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Merk Kendaraan Bermotor</name>
   <tag></tag>
   <elementGuidId>dc78e668-5014-4f1f-bfdd-fb4e5203b536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'HONDA' or . = 'HONDA')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-63-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-63-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2d5f944-d691-4091-8f45-87e22269e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>7b999fc2-1307-4ccc-8c49-61ae27a7e063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-33-option-${id}</value>
      <webElementGuid>096d6d38-1f6c-4229-be56-5322d229715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>69be7c6f-a30f-4ef3-a606-bae73a282ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HONDA</value>
      <webElementGuid>30af169f-18e0-4651-a273-d54c330ceef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-63-option-${id}&quot;)</value>
      <webElementGuid>d5b77688-b64e-47d6-89a9-1725ab429397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-63-option-1']</value>
      <webElementGuid>ab5223b0-66c0-492b-83ff-e25beee11e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJAJ'])[1]/following::div[1]</value>
      <webElementGuid>6390cca4-634d-44e6-85b6-9d7fe94db8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Merk ...'])[1]/following::div[9]</value>
      <webElementGuid>898b5e97-9014-4fa4-abb5-b0119a6d229b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAWASAKI'])[1]/preceding::div[1]</value>
      <webElementGuid>e36deda9-0b0a-4f1c-84a2-10d64b4b10e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIAGGIO / VESPA'])[1]/preceding::div[2]</value>
      <webElementGuid>f5110390-a2f7-4c18-a6fa-30b2b6467748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HONDA']/parent::*</value>
      <webElementGuid>2aeeadb6-342e-4c8e-9767-dedf15482604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>f701f2ce-a97c-46c1-8259-b915304920e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-63-option-1' and (text() = 'HONDA' or . = 'HONDA')]</value>
      <webElementGuid>156dd24e-262b-40c6-97af-a7f059b3942d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
