<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Cabang</name>
   <tag></tag>
   <elementGuidId>b957fa1b-16c9-41cd-85f2-595b6c5ac882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-27-option-${id}&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-27-option-41']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-27-option-41</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0acba27-e184-43ec-98c2-2449348bb151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>3c005b1a-dd50-494e-b60b-1df39fc5c46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-27-option-41</value>
      <webElementGuid>4696683a-c09e-4afa-935b-816faa7b1633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>67451697-da18-417c-b035-ad43d5b13218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOGOR</value>
      <webElementGuid>79fdbe39-8243-472a-98c0-093b7029d9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-27-option-${id}&quot;)</value>
      <webElementGuid>ccc276c3-513e-463a-a9d7-a303a225d800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-27-option-41']</value>
      <webElementGuid>0fa3e0f3-ec51-40a8-922f-66c4a2ff050d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bogo'])[1]/following::div[5]</value>
      <webElementGuid>27d17386-6ae9-468b-8c6e-29e85b106bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[22]/following::div[11]</value>
      <webElementGuid>a2e4e472-c9ff-48da-988a-6df9c0406ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/preceding::div[1]</value>
      <webElementGuid>145d80b4-f4a6-495b-8f1d-f833d94133ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/div/div[2]/div/div</value>
      <webElementGuid>2ceee258-c443-4dac-aa72-466c47bf47e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-27-option-41' and (text() = 'BOGOR' or . = 'BOGOR')]</value>
      <webElementGuid>507cc59a-6cdb-445f-bef9-be46fb7de4c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
