<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Kode Pos</name>
   <tag></tag>
   <elementGuidId>dae2400c-f840-4259-b5aa-2f82a0e768b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-26-option-${id}&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-26-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-26-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75a45be6-df10-4e58-9dcf-5452b820ab99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>f0952710-55d4-4abe-8036-7cf16c655fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-26-option-0</value>
      <webElementGuid>8ca03427-8b34-47da-bd98-8aacaf49342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fa607738-f856-4fec-a31d-c23e1c67756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16132</value>
      <webElementGuid>24752da7-1c04-4862-8b60-01fc59f8c442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-26-option-${id}&quot;)</value>
      <webElementGuid>bc07cfc4-ff67-483a-a56c-ea3cc4cb1e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-26-option-0']</value>
      <webElementGuid>48692bad-5bb7-4e81-bcdf-c7fac9cec874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kode Pos ...'])[1]/following::div[8]</value>
      <webElementGuid>812be3f4-9b5e-49e6-9edf-f1cbdbbbf053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/following::div[12]</value>
      <webElementGuid>2cdb00e8-e2f1-43dc-9a37-289523f633bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/preceding::div[1]</value>
      <webElementGuid>9a38828b-8a4a-4479-b310-9c770c43755a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16132']/parent::*</value>
      <webElementGuid>24d619ae-7e4d-492d-9f9e-f017484e4f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div[2]/div/div</value>
      <webElementGuid>18cfd7e0-14d8-4ee0-a604-20f854700a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-26-option-0' and (text() = '16132' or . = '16132')]</value>
      <webElementGuid>5e56bfd4-3896-4a04-b9fe-460c3b01eeaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
