<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Status</name>
   <tag></tag>
   <elementGuidId>3e493910-26ed-40f7-810d-9012c37c1f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-20-option-${id}&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-20-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-20-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e9b0f66-45bb-4dbb-9bfb-d50a3c3d0b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-127f0ei-option</value>
      <webElementGuid>7a3e2a0c-e26c-4364-9a5e-6381c28c518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-20-option-1</value>
      <webElementGuid>e7db9f0c-36ea-4337-8614-314cdbdc8aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4a98dd75-6078-49e4-9fd1-028379350804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KARYAWAN KONTRAK</value>
      <webElementGuid>df73093c-2c35-4d57-89e0-cc4517d72547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-20-option-${id}&quot;)</value>
      <webElementGuid>66a2a43b-8a82-4fce-abc0-7e036eee96a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-20-option-1']</value>
      <webElementGuid>a6753c59-9f06-435b-8f2a-7aeb70e88bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KARYAWAN TETAP'])[1]/following::div[1]</value>
      <webElementGuid>449fceea-c26b-46a0-8089-9ea45da85971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KARYAWAN KONTRAK'])[1]/following::div[9]</value>
      <webElementGuid>b5694599-04cc-429a-9719-48acfd9a8d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::div[2]</value>
      <webElementGuid>dff7adf6-3b2e-4342-a14e-cc160a861b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>8b1fa399-152c-4004-8cb1-2bc63d508ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-20-option-1' and (text() = 'KARYAWAN KONTRAK' or . = 'KARYAWAN KONTRAK')]</value>
      <webElementGuid>622ce58d-3a70-434a-9588-1412848fc8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
