<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Bidang Pekerjaan</name>
   <tag></tag>
   <elementGuidId>63f59505-fcf4-48ac-90c1-9fe1220d3d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-18-option-${id}&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-18-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-18-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>347affac-fb3c-43ac-966f-4efcb90c4f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>f59375cd-9da5-4d4c-bd32-5832fd55a1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-18-option-1</value>
      <webElementGuid>4f968ce7-9dff-47ff-9795-faf92365920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>948c32ad-5727-47e9-aa92-eeb5056db7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUSTOMER SERVICE</value>
      <webElementGuid>c81ae2ee-274b-45cc-ad67-65e1eb16eb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-18-option-${id}&quot;)</value>
      <webElementGuid>4377c159-e6be-449e-91a6-8ad4293b61b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-18-option-1']</value>
      <webElementGuid>ca02d219-a1d1-4997-aeb3-e5753fb08640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KONSULTAN/ANALIS'])[1]/following::div[1]</value>
      <webElementGuid>4bc15da4-6a25-451d-aff2-4127a60c6c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Bidang Pekerjaan ...'])[1]/following::div[9]</value>
      <webElementGuid>6096a7ce-25ed-41d5-b752-20e81d2804e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EKSEKUTIF'])[1]/preceding::div[1]</value>
      <webElementGuid>82057808-8527-4527-8d2e-ce77a5ffcc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRASI UMUM'])[1]/preceding::div[2]</value>
      <webElementGuid>1c7c21d9-5ba9-4a50-9417-980d6b766267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CUSTOMER SERVICE']/parent::*</value>
      <webElementGuid>b2520de6-68b1-4ede-8cee-d3fac946f3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>4415197d-9d07-412f-afc5-1850c3638ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-18-option-1' and (text() = 'CUSTOMER SERVICE' or . = 'CUSTOMER SERVICE')]</value>
      <webElementGuid>9b20c224-70a8-4415-a29c-cbd2cf08d492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
