<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value jabatan</name>
   <tag></tag>
   <elementGuidId>7c2067f6-5a00-400b-afb4-b3837022861f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-select-19-option-${id}&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-19-option-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-19-option-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>912a7cdd-192c-4c1c-ba59-564f96183eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-158nmiz-option</value>
      <webElementGuid>b66c51fd-0a23-4167-900c-6a0b5e5af5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-19-option-8</value>
      <webElementGuid>eb5e266a-f083-41d8-a4c1-9a3e1dc868c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a86e07c2-278f-46e4-ace3-ede1ffcbc180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOORDINATOR</value>
      <webElementGuid>3ffcbeb0-02fa-4e56-a0c1-f09222eec31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-19-option-${id}&quot;)</value>
      <webElementGuid>3eff801c-0a7c-46e3-a7b9-a19949e9a787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-19-option-8']</value>
      <webElementGuid>157c1c7c-96bb-42c1-8003-abc22ffc318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEPALA SEKOLAH'])[1]/following::div[1]</value>
      <webElementGuid>29c2ea47-9bdf-4e4e-8ef5-c5e0417c2f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEPALA BAGIAN'])[1]/following::div[2]</value>
      <webElementGuid>16382534-dafc-4c54-a08a-6c06630f9c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANAGER'])[1]/preceding::div[1]</value>
      <webElementGuid>27ebf250-b81a-4194-a72a-7fd31df6d1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANDOR'])[1]/preceding::div[2]</value>
      <webElementGuid>f265bc91-97a0-4386-b399-5c7d6f5f4705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOORDINATOR']/parent::*</value>
      <webElementGuid>e7b35109-0f0a-40a3-b34e-291ded2589db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[9]</value>
      <webElementGuid>f3a081e0-8555-4b46-90c1-95f163faab6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-19-option-8' and (text() = 'KOORDINATOR' or . = 'KOORDINATOR')]</value>
      <webElementGuid>977b16b5-0373-4349-9e06-12e942c974e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
