<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Masa Berlaku KTP Seumur Hidup</name>
   <tag></tag>
   <elementGuidId>66d5ac19-8093-4e46-9ba3-9785fcf0cae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div[2]/div/div/div/div[2]/div/div[7]/div/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.custom-checkbox.custom-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b35b529-bb3b-4e1f-af23-3873e0ecee8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox custom-control</value>
      <webElementGuid>47dc5629-c072-47e0-97c5-93c64bad9f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[1]/div/div/div[2]/div/div/div/div[2]/div/div[7]/div/label</value>
      <webElementGuid>0d804663-f33e-42d3-b23f-f4bc6711aa68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[6]</value>
      <webElementGuid>70795daf-5483-4372-bd87-aab555340c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::div[2]</value>
      <webElementGuid>16c201b6-1676-45bf-b342-803104f90907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>300a67c2-5e51-430e-8ca1-1ee5d4b2b90f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
