<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_WAKTU10.30</name>
   <tag></tag>
   <elementGuidId>ffc8dc40-3897-4c33-a489-a1904ca2c0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='mytable']/tbody/tr[10]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c6c8614d-375f-4c90-b8fa-2f69557f870a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectable-column</value>
      <webElementGuid>1020d09a-e944-4c88-867b-3d3030906360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WAKTU10.30</value>
      <webElementGuid>c61260d6-6e38-487c-a830-9d7259508c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mytable&quot;)/tbody[@class=&quot;body-custom&quot;]/tr[10]/td[@class=&quot;selectable-column&quot;]</value>
      <webElementGuid>1fb96173-ee81-4e49-97dd-86dcd835a081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mytable']/tbody/tr[10]/td[4]</value>
      <webElementGuid>b12de5b7-f4c5-4762-a335-14b72950c2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey KPM'])[1]/following::td[1]</value>
      <webElementGuid>04ad5484-dac0-45e2-a7bf-2511a907e8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEWI'])[1]/following::td[1]</value>
      <webElementGuid>b29a176c-3176-48e5-9745-e586005264ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKTU'])[67]/preceding::td[1]</value>
      <webElementGuid>fa44903b-656e-4f26-83a5-7162eb0123c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[4]</value>
      <webElementGuid>c81fded7-efbf-4f00-b581-77b1e1b93e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'WAKTU10.30' or . = 'WAKTU10.30')]</value>
      <webElementGuid>9469b63b-7aa5-43a5-a393-e0fdd31cf86f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
