<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan Konsumen R2</name>
   <tag></tag>
   <elementGuidId>d2f6d82e-f056-4e48-8fe0-d72de1e99553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul[3]/li/div/ul/li[2]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58431744-05b3-4aa8-acec-a97de85da3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>e3f8c3ac-097a-4327-a1c2-8b7a78727721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan Konsumen R2</value>
      <webElementGuid>f6d12310-b387-4202-9770-fe1467ae2680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-wrapper app-sidebar-fixed app-header-fixed&quot;]/div[1]/div[@class=&quot;app-sidebar app-sidebar--dark&quot;]/div[@class=&quot;app-sidebar--content&quot;]/div[@class=&quot;scrollbar-container ps ps--active-y&quot;]/div[@class=&quot;sidebar-navigation&quot;]/ul[3]/li[1]/div[@class=&quot;collapse show&quot;]/ul[1]/li[2]/div[@class=&quot;collapse show&quot;]/ul[1]/li[2]/a[@class=&quot;pointer&quot;]</value>
      <webElementGuid>19218587-0194-4b7c-8f0e-dfcbd000fbec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul[3]/li/div/ul/li[2]/div/ul/li[2]/a</value>
      <webElementGuid>32aef07c-2cb8-47f8-bd0b-90b4b7cc961e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Up Prospek'])[1]/following::a[1]</value>
      <webElementGuid>2c85c54f-3043-42de-83f4-d3dac32402b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Pendataan'])[1]/following::a[2]</value>
      <webElementGuid>d4af07b5-6e15-4dcc-8cd7-5f0740839ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplikasi Masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>67be1195-ef58-48e5-8c32-2ddb2e740f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a</value>
      <webElementGuid>926d1848-813c-4438-800d-1b29af5802df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Pengajuan Konsumen R2' or . = 'Pengajuan Konsumen R2')]</value>
      <webElementGuid>489ebf05-a03a-4d76-8692-bdf5890edde1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
