<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_R2</name>
   <tag></tag>
   <elementGuidId>58710aed-b862-4f57-ae9f-468b95e9e953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul[3]/li/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8388cde-0ca2-4b62-bc08-648f69d6a101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>14117925-1573-4eab-a954-39ec6db876be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R2</value>
      <webElementGuid>5da16f66-9f4a-4522-b81e-5d8ab658e740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-wrapper app-sidebar-fixed app-header-fixed&quot;]/div[1]/div[@class=&quot;app-sidebar app-sidebar--dark&quot;]/div[@class=&quot;app-sidebar--content&quot;]/div[@class=&quot;scrollbar-container ps&quot;]/div[@class=&quot;sidebar-navigation&quot;]/ul[3]/li[1]/div[@class=&quot;collapse show&quot;]/ul[1]/li[2]/a[@class=&quot;pointer&quot;]</value>
      <webElementGuid>4a93b912-cea7-44c2-b4b1-e9be47473637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul[3]/li/div/ul/li[2]/a</value>
      <webElementGuid>59615185-d20a-4ae2-82bc-d71164007bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Kode'])[1]/following::a[1]</value>
      <webElementGuid>15fdd4b1-89f5-4741-bdf3-940973d7fbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Prospek'])[2]/following::a[2]</value>
      <webElementGuid>1121411e-2fa9-48b7-92a2-b009d28e04e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funnel KPM'])[1]/preceding::a[1]</value>
      <webElementGuid>aa30d8a7-5f21-42a4-bbab-0a6bcead6821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/div/ul/li[2]/a</value>
      <webElementGuid>6919820b-9701-4733-a7f3-ffa4aa5682b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'R2' or . = 'R2')]</value>
      <webElementGuid>25e41605-a8e9-4508-86d6-f37def60a35d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
